QrCodeWithParameter/Models/QuestionDetails.cs
using QrCodeWithParameter.Models.UserDetails;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace QrCodeWithParameter.Models
{
    public class QuestionDetails
    {
        [Key]
        [StringLength(36)]
        public string QuestionId { get; set; }

        [StringLength(350)]
        public string QuestionTitle { get; set; }

        [StringLength(36)]
        public string folderId { get; set; }

        [StringLength(100)]
        public string CreatedBy { get; set; }

        [StringLength(36)]
        public string CreatorId { get; set; }

        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

QrCodeWithParameter/Controllers/QuestionDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QrCodeWithParameter.DBContext;
using QrCodeWithParameter.Models;
using QrCodeWithParameter.Models.UserDetails;
using QrCodeWithParameter.Services;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace QrCodeWithParameter.Controllers
{
    [Authorize]
    public class QuestionDetailsController : Controller
    {
        private readonly QrCodeWithParameterDBContext _context;
        private readonly UserManager<ApplicationUser> userManager;

        public QuestionDetailsController(QrCodeWithParameterDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

       
        [AllowAnonymous]
        // GET: QuestionDetails
        public async Task<IActionResult> Index()
        {
            //var applicationUser = new ApplicationUser();
            var currentUser = this.userManager.GetUserId(User);
            var qrContext = _context.QuestionDetails.Include(e => e.ApplicationUser).Where(e=>e.CreatorId == currentUser);
            return View(await _context.QuestionDetails.ToListAsync());
        }

       
        // GET: QuestionDetails/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var questionDetails = await _context.QuestionDetails
                .FirstOrDefaultAsync(m => m.QuestionId == id);           

            var currentUserId = userManager.GetUserId(User);
            var videoDetails = new VideoDetails();
            var videoId = await _context.AnswerDetails.Where(a => a.UserId == currentUserId).Select(a => a.VideoId).FirstOrDefaultAsync();
            var userName = User.Identity.Name;

            var applicationUsers = new ApplicationUser();

            List<string> videoIds = new List<string>();
            if (User.IsInRole("Admin"))
            {
               videoIds = await _context.AnswerDetails.Where(a => a.ParentFolderId == questionDetails.folderId).Select(a => a.VideoId).ToListAsync();
            }
            else
            {
                videoIds = await _context.AnswerDetails.Where(a => a.UserId == currentUserId).Where(a=>a.ParentFolderId == questionDetails.folderId).Select(a => a.VideoId).ToListAsync();
            }       


            ViewBag.VideoId = videoIds;
            //ViewBag.UserName = userName;

            //var answerDetails = new AnswerDetails();
           // var userId = await _context.AnswerDetails.Where(x => x.ParentFolderId == questionDetails.folderId).Select(x => x.UserId).ForEachAsync();
            //var userName = await 

            if (questionDetails == null)
            {
                return NotFound();
            }

            return View(questionDetails);
        }

        // GET: QuestionDetails/Create
        public IActionResult Create()
        {
            var questionDetails = new QuestionDetails();
            //questionDetails.CreatorId = this.userManager.GetUserId(HttpContext.User);
            questionDetails.CreatedBy = this.userManager.GetUserName(HttpContext.User);
            return View(questionDetails);
        }

        // POST: QuestionDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(QuestionDetails questionDetails,[FromForm] string description, [FromForm] string name)
        {
            var folderID = Guid.NewGuid().ToString();
            var folderDetails = new FolderDetails();
            folderDetails.Description = description;
            folderDetails.ID = folderID;
            folderDetails.isActive = true;
            folderDetails.Name = name;

            var applicationUser = new ApplicationUser();
            

            questionDetails.QuestionId = Guid.NewGuid().ToString();
            questionDetails.folderId = folderID;
            //var creatorId = userManager.Users.Where(a=> a.Email == "gautamash9@gmail.com").Select(a => a.Id);
            questionDetails.CreatorId = this.userManager.GetUserId(User);

            //questionDetails.CreatorId = this.userManager.GetUserId(HttpContext.User);
            //var creatorId = await _context.;
            /**var creatorID = userManager.Users.Select(a=>a.Id)
                .Where(Equals("GAUTAMASH9@GMAIL.COM"))
                .ToList();**/

            /**var creatorID = userManager.Users.
            .FromSqlRaw(@"SELECT id FROM applicationuser WHERE Name = {0}", "John Doe")
            .FirstOrDefault();**/

           // var currentUser = this.userManager.GetUserId(User);
            questionDetails.CreatedBy = User.Identity.Name;
            if (ModelState.IsValid)
            {
                _context.Add(questionDetails);
                await _context.SaveChangesAsync();

                ApiService apiService = new ApiService();
                var response =  apiService.CreateFolder(folderDetails);

                return RedirectToAction(nameof(Index));
            }
            return View(questionDetails);
        }

        // GET: QuestionDetails/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var questionDetails = await _context.QuestionDetails.FindAsync(id);
            if (questionDetails == null)
            {
                return NotFound();
            }
            return View(questionDetails);
        }

        // POST: QuestionDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("QuestionId,QuestionTitle,folderId,CreatedBy,CreatorId")] QuestionDetails questionDetails)
        {
            if (id != questionDetails.QuestionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(questionDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuestionDetailsExists(questionDetails.QuestionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(questionDetails);
        }

        // GET: QuestionDetails/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var questionDetails = await _context.QuestionDetails
                .FirstOrDefaultAsync(m => m.QuestionId == id);
            if (questionDetails == null)
            {
                return NotFound();
            }

            return View(questionDetails);
        }

        // POST: QuestionDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var questionDetails = await _context.QuestionDetails.FindAsync(id);
            _context.QuestionDetails.Remove(questionDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuestionDetailsExists(string id)
        {
            return _context.QuestionDetails.Any(e => e.QuestionId == id);
        }
    }
}

QrCodeWithParameter/Controllers/VideoDetailsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QrCodeWithParameter.DBContext;
using QrCodeWithParameter.Models;
using QrCodeWithParameter.Models.UserDetails;
using QrCodeWithParameter.Services;

namespace QrCodeWithParameter.Controllers
{
    public class VideoDetailsController : Controller
    {
        private readonly QrCodeWithParameterDBContext _context;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly UserManager<ApplicationUser> userManager;

        public VideoDetailsController(QrCodeWithParameterDBContext context,IWebHostEnvironment hostingEnvironment,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
        }

        // GET: VideoDetails
        public async Task<IActionResult> Index()
        {
            return View(await _context.VideoDetails.ToListAsync());
        }

        // GET: VideoDetails/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videoDetails = await _context.VideoDetails
                .FirstOrDefaultAsync(m => m.videoID == id);
            if (videoDetails == null)
            {
                return NotFound();
            }

            return View(videoDetails);
        }

        [HttpGet]
        // GET: VideoDetails/Create
        public IActionResult Create(string id)
        {
            /**var folderList = (from folder in _context.FolderDetails
                              select new SelectListItem()
                              {
                                  Text = folder.Name,
                                  Value = folder.ID.ToString(),
                              }).ToList();
            folderList.Insert(0, new SelectListItem()
            {
                Text = "------Select--------",
                Value = string.Empty
            });

            VideoDetails videoDetails = new VideoDetails();
            videoDetails.listOfFolders = folderList;**/

            //var answerDetails = new AnswerDetails();
            //answerDetails.ParentFolderId = id;

            return View();
        }

        // POST: VideoDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VideoDetails videoDetails,[FromForm] string answer, string id)
        {
            var answerDetails = new AnswerDetails();
            var folderDetails = new FolderDetails();
            var questionDetail = new QuestionDetails();

            var questionId = await _context.QuestionDetails.Where(x => x.folderId == id).Select(x => x.QuestionId).FirstOrDefaultAsync();
            var folderID = Guid.NewGuid().ToString();
            var videoID = Guid.NewGuid().ToString();

            folderDetails.ID = folderID;
            folderDetails.Description = "";
            folderDetails.createdBy = User.Identity.Name;
            folderDetails.isActive = true;
            folderDetails.Name = User.Identity.Name;

            ApiService apiService = new ApiService();
            var response = apiService.CreateFolder(folderDetails);

            answerDetails.AnswerID = Guid.NewGuid().ToString();
            answerDetails.FolderId = folderID;
            //var userId = userManager.Users.Where(a => a.Email == "test@test.com").Select(a => a.Id);
            answerDetails.UserId = this.userManager.GetUserId(User);
            answerDetails.ParentFolderId = id;
            answerDetails.AnswerValue = answer;
            answerDetails.VideoId = videoID;

            videoDetails.videoID = videoID;
            
            string fileName = videoDetails.detailsVideo.FileName.ToString();
            string basePath = Path.Combine(hostingEnvironment.WebRootPath, "files\\");
            bool pathExists = System.IO.Directory.Exists(basePath);
            if (!pathExists)
            {
                Directory.CreateDirectory(basePath);
            }
            videoDetails.folderID = videoDetails.folderID;
            var filePath = Path.Combine(basePath, videoDetails.videoID+".mp4");
            videoDetails.videoURL= Path.Combine(filePath);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await videoDetails.detailsVideo.CopyToAsync(stream);
            }

            if (ModelState.IsValid)
            {
                _context.Add(videoDetails);
                await _context.SaveChangesAsync();

                _context.Add(answerDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "QuestionDetails",new { id = questionId});
            }
            return RedirectToAction("QuestionDetails","Index");
        }

        // GET: VideoDetails/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videoDetails = await _context.VideoDetails.FindAsync(id);
            if (videoDetails == null)
            {
                return NotFound();
            }
            return View(videoDetails);
        }

        // POST: VideoDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("videoID,videoTitle,videoURL,folderID,CreatedDate")] VideoDetails videoDetails)
        {
            if (id != videoDetails.videoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(videoDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VideoDetailsExists(videoDetails.videoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(videoDetails);
        }

        // GET: VideoDetails/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videoDetails = await _context.VideoDetails
                .FirstOrDefaultAsync(m => m.videoID == id);
            if (videoDetails == null)
            {
                return NotFound();
            }

            return View(videoDetails);
        }

        // POST: VideoDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var videoDetails = await _context.VideoDetails.FindAsync(id);
            _context.VideoDetails.Remove(videoDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VideoDetailsExists(string id)
        {
            return _context.VideoDetails.Any(e => e.videoID == id);
        }
    }
}

QrCodeWithParameter/Views/QuestionDetails/Create.cshtml
@model QrCodeWithParameter.Models.QuestionDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>QuestionDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="desciption">Description</label>
                <input type="text" class="form-control" name="description" />
            </div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" />
            </div>
            <div class="form-group">
                <label asp-for="QuestionTitle" class="control-label"></label>
                <input asp-for="QuestionTitle" class="form-control" />
                <span asp-validation-for="QuestionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

QrCodeWithParameter/Views/QuestionDetails/Delete.cshtml
@model QrCodeWithParameter.Models.QuestionDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuestionDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuestionTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.folderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.folderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatorId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="QuestionId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

QrCodeWithParameter/Views/QuestionDetails/Details.cshtml
@model QrCodeWithParameter.Models.QuestionDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .row {
        display: flex;
        flex-wrap: wrap;
    }

</style>
<h1>Details</h1>
<p>
    <a asp-controller="VideoDetails" asp-action="Create" asp-route-id="@Model.folderId">Create New</a>
</p>
<div>
    <h4>QuestionDetails</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.QuestionTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.folderId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.folderId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatorId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatorId)
        </dd>
    </dl>
</div>
<div class="row">
    
        @foreach (var ids in ViewBag.VideoId)
        {
        <div class="col-sm-3">
            <a asp-controller="VideoDetails" asp-action="Details" asp-route-id="@ids">
                <div class="card">
                    <img src="https://hatrabbits.com/wp-content/uploads/2018/10/risky-assumptions.jpg" class="card-img-top" alt="text" />
                    <div class="card-body">
                        <h5 class="card-title">
                            Click here
                        </h5>
                    </div>
                </div>


            </a>
        </div>
        }
    
</div>


<div>
    <a asp-action="Edit" asp-route-id="@Model.QuestionId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

QrCodeWithParameter/Views/QuestionDetails/Edit.cshtml
@model QrCodeWithParameter.Models.QuestionDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>QuestionDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="QuestionId" />
            <div class="form-group">
                <label asp-for="QuestionTitle" class="control-label"></label>
                <input asp-for="QuestionTitle" class="form-control" />
                <span asp-validation-for="QuestionTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="folderId" class="control-label"></label>
                <input asp-for="folderId" class="form-control" />
                <span asp-validation-for="folderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatorId" class="control-label"></label>
                <input asp-for="CreatorId" class="form-control" />
                <span asp-validation-for="CreatorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

QrCodeWithParameter/Views/QuestionDetails/Index.cshtml
@model IEnumerable<QrCodeWithParameter.Models.QuestionDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.QuestionTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.folderId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatorId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.folderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatorId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.QuestionId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.QuestionId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.QuestionId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>